//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesProject_Ec
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressDetail
    {
        public int ID { get; set; }
        public string AdressLine1 { get; set; }
        public string Adressline2 { get; set; }
        public string City { get; set; }
        public string StateName { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public int MemberID { get; set; }
    }
}
